using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using filter = System.Func<Aurum.SQL.SqlColumnInfo, bool>;
using Lookup = System.Collections.Generic.Dictionary<string, string>;

namespace Aurum.SQL
{
	public class TemplateMaterializer
	{
		IList<SqlQueryTemplate> _templates;
		static readonly IDictionary<string, filter> _filters = new Dictionary<string, filter>
		{
			{"all", λ => true },
			{"*", λ => true },
			{"identity", λ => λ.Identity},
			{"!identity", λ => !λ.Identity}
			//TODO: Defaulted/Autogenerated Columns
			//TODO: Contains
			//TODO: Type
			
		};
		
		public TemplateMaterializer(IList<SqlQueryTemplate> templates)
		{
			_templates = templates;
		}

		public List<SqlQueryDefinition> Build(SqlTableInfo table)
		{
			var lookup = BuildStrings(table);

			return _templates
				.Where(t => t.AppliesTo(table))
				.Select(t => Apply(t, table, lookup))
				.ToList();
		} 

		SqlQueryDefinition Apply(SqlQueryTemplate template, SqlTableInfo table, Lookup lookup)
		{
			var def = new SqlQueryDefinition();
			def.GroupName = table.Name;
			def.SourceName = table.Name;
			def.IsModified = false;

			def.Name = Replace(template.QueryName??template.Name, lookup);
			var query = Replace(template.QueryText, lookup);
			def.Query = Parse(query, table.ColumnInfo);

			return def;
		}

		string Replace(string input, Lookup lookup)
		{
			var sb = new StringBuilder(input);
			foreach (var set in lookup) sb.Replace(set.Key, set.Value);
			return sb.ToString();
		}

		string Parse(string query, IEnumerable<SqlColumnInfo> columns)
		{
			var pattern = @"\$\{\|\|\}";
			return query;
			//TODO: Aggregate Logic
		}

		Lookup BuildStrings(SqlTableInfo table)
		{
			var lookup = new Dictionary<string, string>();
			lookup["{schema}"] = table.Schema;
			lookup["{table}"] = table.Name;

			return lookup;
		}

		private string GetIdentity(SqlTableInfo table)
		{
			return table.ColumnInfo
			.Where(c => c.Identity)
			.Select(c => $"[{c.Name}] = @{c.Name}")
			.DefaultIfEmpty()
			.Aggregate((a, b) => $"{a} AND {b}");
		}


		private string GetColumns(SqlTableInfo table, Func<SqlColumnInfo, bool> condition)
		{
			return table.ColumnInfo
			.DefaultIfEmpty()
			.Select(c => $"[{c.Name}]")
			.Aggregate((a, b) => $"{a}, {b}");
		}



	}
}
